version: "3.9"
services:
  commit_history_bff:
    image: commit_history_bff
    build:
      context: ./
      dockerfile: ./Dockerfile
    env_file:
      - .env
    ports:
      - "${PORT}:${PORT}"      